optional dependency issue fix started
aurelio-labs/semantic-router pull request #190
Opened 2024-03-09 16:21 UTC by zahid-syed

2024-03-14 13:05 UTC, ashraq1455 requested changes

2024-03-14 13:05 UTC, ashraq1455 commented on semantic_router/encoders/mistral.py
> +        return client, embedding_response, mistral_exception
```suggestion
        return client, mistralai
```

2024-03-14 13:05 UTC, ashraq1455 commented on semantic_router/encoders/mistral.py
> +            except self._mistral_exception as e:
```suggestion
            except self._mistralai.exceptions.MistralException as e:
```

2024-03-14 13:05 UTC, ashraq1455 commented on semantic_router/encoders/mistral.py
> +            or not isinstance(embeds, self._embedding_response)
```suggestion
            or not isinstance(embeds, self._mistralai.models.embeddings.EmbeddingResponse)
```

2024-03-14 18:28 UTC, ashraq1455 approved these changes
Lg

2024-03-15 02:29 UTC, jamescalam approved these changes
lgtm @zahid-syed, great work

2024-03-15 02:29 UTC, merged